### PR TITLE
Upgrade to golang 1.14

### PR DESCRIPTION
**Pull request by Brian-McM**
## Description

Also ran `make fix` to reformat files that were ill formatted but snuck passed the pre commit hooks.

## Todos
- [ ] Tests
- [ ] Documentation
- [x] Release note

## Release Note

```release-note
Upgrade to golang 1.14
```

### CODE REVIEW

**Comment by bcreane** [comment]
@Brian-McM - does golang v1.14 work with the range of CPU architectures (I thought there was one non-amd64 CPU that didn't build w/v1.14).

**Comment by Brian-McM** [comment]
@bcreane I'm not sure, who would be the best person to discuss this with?

**Comment by bcreane** [comment]
I thought @fasaxc mentioned that golang v1.14 support wasn't mature in one of the non-amd64 architectures? Regardless, @caseydavenport describes that as community supported which shouldn't block our work to upgrade.

Once CI passes, I'll approve.

**Comment by bcreane** [comment]
@Brian-McM - same test has failed twice. Sigh, either broken test, or a consequence of your PR, not sure which.

**Pull request merged**
