### PR TITLE
Remove k8s unversioned

### PR DESCRIPTION
**Pull request by bjwbell**
Fixes https://github.com/projectcalico/libcalico-go/issues/299

### CODE REVIEW

**Comment by caseydavenport** [comment]
Looks like the build is failing to find the meta/v1 package:

```

lib/backend/lib/backend/k8s/thirdparty/global_config.go:8:2: cannot find package "k8s.io/client-go/pkg/apis/meta/v1" in any of:
	/go/src/github.com/projectcalico/libcalico-go/vendor/k8s.io/client-go/pkg/apis/meta/v1 (vendor tree)
	/usr/local/go/src/k8s.io/client-go/pkg/apis/meta/v1 (from $GOROOT)
	/go/src/k8s.io/client-go/pkg/apis/meta/v1 (from $GOPATH)
```

You probably need to remove the pin in `glide.yaml` and update `glide.lock` with `glide up -strip-vendor` so that it picks up the right version of client-go.

**Comment by bjwbell** [comment]
@caseydavenport squash the commits?

**Comment by caseydavenport** [comment]
@bjwbell yes please :)

once squashed this LGTM.  Thanks a lot!

**Comment by caseydavenport** [comment]
@bjwbell OK if I hold off on merging until later this week? We're in the middle of a Calico v2.0.0 release.  I don't think it's a super risky PR, but don't want to be surprised :)

Once that is cut I'll put this in asap.

**Comment by bjwbell** [comment]
@caseydavenport Yes; upgrading k8s is always risky :-).

**Comment by caseydavenport** [comment]
@bjwbell Sorry, looks like this needs a rebase.  I'll merge right after!

**Comment by bjwbell** [comment]
@caseydavenport You can probably merge, looks like the checks passed.

**Comment by caseydavenport** [comment]
Indeed, thanks!

**Pull request merged**
