### PR TITLE
Cleanup wireguard tunnel address

### PR DESCRIPTION
**Pull request by caseydavenport**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
Fix that deleting a node didn't release its wireguard tunnel address
```

### CODE REVIEW

**Review by robbrockbank — APPROVED** [review]
lgtm

**Comment by marvin-tigera** [comment]
OK, Adding "merge-when-ready" label and will merge the PR when it's ready.

**Comment by caseydavenport** [comment]
Hey Marvin get to work

**Comment by marvin-tigera** [comment]
OK, removing "merge-when-ready" label, PR will need to be manually merged when ready

**Comment by caseydavenport** [comment]
Its OK @marvin-tigera, you tried. Better luck next time.

**Pull request merged**
