### PR TITLE
Make test-containerized target more reliable

### PR DESCRIPTION
**Pull request by neiljerram**
Wait until the API server is responding, before starting to run tests.

### CODE REVIEW

**Comment by tmjd** [comment]
Thanks Neil, I have been hitting some issues with the tests and I hope this addresses that.
What about moving that check to the run-kubernetes-master target and a comment about why it is there?

**Comment by robbrockbank** [comment]
Neil back with you - I agree with Eriks suggestions ^^^

Back with you.

**Comment by neiljerram** [comment]
@robbrockbank @tmjd Done!

**Comment by robbrockbank** [comment]
LGTM

**Pull request merged**
