### PR TITLE
Don't allow creating resource with no name

### LINKED ISSUE #641: Creating a pool without a name should return an error
Creating a pool without a name should return an error

## Expected Behavior

I'd expect an error to be returned.

## Current Behavior

Pool creation silently fails

## Possible Solution

Pool creation should return an error when no name is supplied.

## Steps to Reproduce (for bugs)

```
pool := api.IPPool{
				Spec: api.IPPoolSpec{
					CIDR: "192.168.0.0/16",
				},
			}
			_, err := calicoClient.IPPools().Create(context.Background(), &pool, options.SetOptions{})
			Expect(err).To(HaveOccurred())
```
## Context

Was trying to create a pool then create an affinity block within the pool. But was receiving an error that `The requested CIDR (192.168.0.0/24) is not within any configured pools.`. Realized that my pool wasn't being created because I had forgotten to give the pool a name. But it was silently failing pool creation.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by neiljerram**
Fixes #641

### CODE REVIEW

**Comment by caseydavenport** [comment]
Looks good to me, but @robbrockbank should look at this to see how it overlaps with any other validation work in the pipeline.

**Comment by robbrockbank** [comment]
LGTM too, but this does overlap with the validation logic - and should be covered by the validation handling.  We can merge now if we think it makes sense to, or hold off and wait for the validator updates that should be coming within the next day or two.

**Comment by caseydavenport** [comment]
@robbrockbank so long as the validation logic covers this, then I think we should fix #641 in that PR rather than this one.

I don't think there's any urgency to fixing this so long as it gets done.

**Comment by neiljerram** [comment]
@robbrockbank @caseydavenport OTOH, this fix is ready now, and might usefully catch something (misconceived setup, I guess) before the rest of validation lands; and it can always be reverted by the validation PR.  So I think there's a case for merging this anyway - WDYT?

**Comment by caseydavenport** [comment]
SGTM - let's merge and make sure to revert / move into the validation code once it exists.

CC @gunjan5

**Pull request merged**
