### PR TITLE
replaces unicode quotation marks in code comments with ascii double quotes

### PR DESCRIPTION
**Pull request by marshallford**
## Description
See title. Also fixes some unicode apostrophes as well. bug fix. A step towards resolving https://github.com/projectcalico/calico/issues/3846 and related to https://github.com/projectcalico/libcalico-go/pull/1289.

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
@marshallford thank you!

What do you think about some sort of check or test to make sure these don't accidentally get added back? They're pretty hard to spot in a code-review, and I'm assuming they are being added accidentally.

**Review by caseydavenport — APPROVED** [review]
LGTM! A follow on with a test would be great, but this is useful on its own so merging now.

**Comment by marshallford** [comment]
> What do you think about some sort of check or test to make sure these don't accidentally get added back? They're pretty hard to spot in a code-review, and I'm assuming they are being added accidentally.

That sounds like a great follow on PR!

**Pull request merged**
