### PR TITLE
Defensively reconnect to etcd if we get repeated timeouts.

### LINKED ISSUE #351: Force a resync if too many Syncer failures
After discussing #343 with @robbrockbank, we think we should be more defensive and break out of the watch loop if we hit too many failures.

### PR DESCRIPTION
**Pull request by fasaxc**
@robbrockbank Was this what you were thinking of?  Note: I haven't tested it yet.

Fixes #351

### CODE REVIEW

**Comment by robbrockbank** [comment]
@fasaxc Ah yes!  That's what I was thinking! :-)

**Comment by fasaxc** [comment]
Assigning back to me to get some UT in place...

**Comment by caseydavenport** [comment]
@fasaxc what's next with this PR? Let's close it if we're not planning on getting it in soon.

**Comment by caseydavenport** [comment]
No response, closing this.

**Comment by fasaxc** [comment]
Please don't close my PRs.

**Pull request closed without merging**
