### PR TITLE
Always update k8s backend label cache (fixes #368)

### LINKED ISSUE #368: k8s driver label cache doesn't get purged for resync deletes
In a scale test [1] that does 10 cycles of creating and deleting 10k pods, I see that in the 3rd cycle Felix only reports 9046 known endpoints (`felix_cluster_num_workload_endpoints`).  So 954 endpoints got missed somehow.

Investigation of a debug log reveals 954 instances of

    <time> [DEBUG][104] syncer.go 618: Skipping pod event - labels didn't change: <name>

Drilling down on that for a particular <name> shows:

```
2017-03-15 11:53:17.170 [DEBUG][104] syncer.go 609: Skipping pod with no IP: ns2--115/001115
2017-03-15 11:53:17.878 [DEBUG][104] syncer.go 104: Update tracker: WorkloadEndpoint(node=remote-host-0, orchestrator=k8s, workload=ns2--115.001115, name=eth0): 45264
2017-03-15 11:54:43.052 [DEBUG][104] syncer.go 333: Cached key not in snapshot: WorkloadEndpoint(node=remote-host-0, orchestrator=k8s, workload=ns2--115.001115, name=eth0)
2017-03-15 11:54:43.075 [INFO][104] syncer.go 337: Sending snapshot deletes: <a long list including workload=ns2--115.001115>
2017-03-15 11:54:43.156 [DEBUG][104] syncer.go 101: Delete from tracker: WorkloadEndpoint(node=remote-host-0, orchestrator=k8s, workload=ns2--115.001115, name=eth0)
2017-03-15 11:55:28.170 [DEBUG][104] syncer.go 609: Skipping pod with no IP: ns2--115/001115
2017-03-15 11:55:28.173 [DEBUG][104] syncer.go 618: Skipping pod event - labels didn't change: ns2--115/001115
2017-03-15 11:56:53.367 [DEBUG][104] syncer.go 618: Skipping pod event - labels didn't change: ns2--115/001115
2017-03-15 11:56:53.371 [DEBUG][104] syncer.go 599: Delete for pod ns2--115/001115
```

What happened was that the first use of that pod name was deleted by a resync, and that code misses cleaning out `syn.labelCache` for the deleted workloads.  So then when we see that workload name again, we wrongly fail to pass it on to Felix.

### PR DESCRIPTION
**Pull request by neiljerram**

### CODE REVIEW

**Comment by neiljerram** [comment]
@caseydavenport @robbrockbank I think this is a candidate for adding into 2.1.0, as it fixes:

- failure to notify Felix about a pod, when a pod name is reused, and the deletion of the previous pod with that name was handled by snapshot/resync processing

- a corresponding memory leak (`syn.tracker[workloadId]`).

WDYT?

**Comment by caseydavenport** [comment]
@tomdee I'd like to add this to v2.1 provided it's OK with you!

**Comment by caseydavenport** [comment]
@neiljerram could you raise an issue to add a UT / FV for this?

#362 adds some FV infrastructure that would allow it but it's not merged yet.

**Comment by caseydavenport** [comment]
Otherwise, LGTM

**Pull request merged**
