### PR TITLE
libcalico pool unit tests

### PR DESCRIPTION
**Pull request by gunjan5**
**Test cases**:
**Test 1**: IPv4 with non-default values for IPIP, NATOut, IPAM - assert the returned Metadata and Spec values.
**Test 2**: IPv4 with default values for IPIP, NATOut, IPAM - assert the returned Metadata and Spec values.
**Test 3**: IPv6 with non-default bools for IPIP, NATOut, IPAM - assert the returned Metadata and Spec values.

### CODE REVIEW

**Comment by gunjan5** [comment]
54.3% coverage (includes 3 big functions in pool.go)

**Comment by fasaxc** [comment]
TODO:
- [ ] Fix up imports to use projectcallico instead of tigera

**Comment by caseydavenport** [comment]
@gunjan5 I think a rebase against master will fix that for you.

**Comment by gunjan5** [comment]
@caseydavenport done! PTAL

**Comment by gunjan5** [comment]
Don't merge this. Need to modify these tests for the changes in PR #181

**Comment by gunjan5** [comment]
Tests passing now

**Pull request closed without merging**
