### PR TITLE
Fix panic caused by Node IP being passed through as (*net.IP)(nil).

### PR DESCRIPTION
**Pull request by fasaxc**
- Fix that our IP object couldn't be stringified if it was nil.
- Fix the node conversion to convert to a nil interface.

### CODE REVIEW

**Comment by caseydavenport** [comment]
Actually, there are a couple of failing tests.

**Comment by fasaxc** [comment]
Ugh, it doesn't seem to be possible to fix this without a big rework.  If you add a `String()` method with a pointer receiver then you lose the automatic call through to the value-receiver version on the unnamed field that was being used by `fmt.Sprintf()`.  You can't have both because go doesn't support overloading and adding a value-receiver version doesn't fix the problem.

**Comment by caseydavenport** [comment]
Given we merged https://github.com/projectcalico/libcalico-go/pull/449,  think we should close this.

Sounds like the String() stuff is a larger rework and we've solved the immediate problem at hand.

**Comment by caseydavenport** [comment]
Added this guy: https://github.com/projectcalico/libcalico-go/issues/452

**Pull request closed without merging**
